# Generated by Django 4.0.6 on 2022-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_owner',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user_customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key'),
        ),
        migrations.AlterField(
            model_name='user_customer',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user_customer',
            name='number',
            field=models.CharField(max_length=13, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user_owner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Primary Key'),
        ),
        migrations.AlterField(
            model_name='user_owner',
            name='number',
            field=models.CharField(max_length=13, verbose_name='전화번호'),
        ),
    ]
